version: '3.8'

services:
  app:
    image: nginx:latest
    container_name: webapp
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      NODE_ENV: "production"
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: password123
      DB_NAME: my_database
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redispass123
    depends_on:
      - database
      - redis
    networks:
      - app_network
    volumes:
      - ./app:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  database:
    image: postgres:alpine
    container_name: db
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: cache
    restart: unless-stopped
    command: redis-server --requirepass redispass123
    ports:
      - "6379:6379"
    networks:
      - app_network
    volumes:
      - redis_data:/data


volumes:
  pg_data:
  redis_data:


networks:
  app_network:
    driver: bridge
